In [6]:
import torch
import numpy as np

In [2]:
x = torch.Tensor([5, 3])
y = torch.Tensor([2, 1])

x*y

tensor([10.,  3.])

In [4]:
x = torch.zeros([2, 5])
x

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [5]:
x.shape

torch.Size([2, 5])

In [11]:
y = torch.rand([2,5])
y

tensor([[0.5690, 0.2889, 0.0738, 0.6783, 0.9841],
        [0.0498, 0.1296, 0.9116, 0.2978, 0.7106]])

In [17]:
y.view([1,-1])

tensor([[0.5690, 0.2889, 0.0738, 0.6783, 0.9841, 0.0498, 0.1296, 0.9116, 0.2978,
         0.7106]])

In [13]:
y

tensor([[0.5690, 0.2889, 0.0738, 0.6783, 0.9841],
        [0.0498, 0.1296, 0.9116, 0.2978, 0.7106]])